title: Diegofelipere | Portafolio QA Tester en Videojuegos
description: Portafolio de proyectos y experiencia en pruebas manuales de videojuegos.
theme: minima
markdown: kramdown

# Navegación del header
header_pages:
  - about.md
  - proyectos.md
