title: Diegofelipere Portafolio
description: QA Tester | Proyectos y Contacto
theme: minima
markdown: kramdown

# Navegación del header
header_pages:
  - about.md
  - proyectos.md
  
minima:
  skin: dark
  social_links:
    - platform: github
      user_url: https://github.com/diegofelipere
    - platform: linkedin
      user_url: https://linkedin.com/in/diegofelipere
    - platform: email
      user_url: mailto:diegofelipere@gmail.com
